### ISSUE TITLE
multicheckbox service no longer exists

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Sharing#28]
On site edit page, settings

```
There was an error.

Zend\ServiceManager\Exception\ServiceNotFoundException: A plugin by the name "multi_checkbox" was not found in the plugin manager Zend\Form\FormElementManager\FormElementManagerV3Polyfill in /var/www/omekas/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php:133
Stack trace:
#0 /var/www/omekas/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php(38): Zend\ServiceManager\AbstractPluginManager->get('multi_checkbox', Array, true)
#1 /var/www/omekas/vendor/zendframework/zend-form/src/Factory.php(111): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->get('multi_checkbox')
#2 /var/www/omekas/vendor/zendframework/zend-form/src/Form.php(176): Zend\Form\Factory->create(Array)
#3 /var/www/omekas/modules/Sharing/Module.php(107): Zend\Form\Form->add(Array)
#4 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Sharing\Module->addSiteEnableCheckbox(Object(Omeka\Event\Event))
#5 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Omeka\Event\Event))
#6 /var/www/omekas/application/src/Controller/SiteAdmin/IndexController.php(115): Zend\EventManager\EventManager->triggerEvent(Object(Omeka\Event\Event))
#7 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\SiteAdmin\IndexController->settingsAction()
#8 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#11 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#12 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#15 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
```

**Comment by zerocrates** [comment]
Zf3 is more strict on case sensitivity of services, including form elements. It's just a matter of getting the correct case. It looks like it will take pretty much any case without the underscore, so `multiCheckbox` should work.
